// <auto-generated />
using System;
using HotelManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.Server.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251208222427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelManagement.API.Models.Cuarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Cuartos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadPersonas = 1,
                            Descripcion = "Habitación individual con vista a la ciudad",
                            Estado = 0,
                            Numero = "101",
                            PrecioPorNoche = 50.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            CapacidadPersonas = 2,
                            Descripcion = "Habitación doble con balcón",
                            Estado = 0,
                            Numero = "102",
                            PrecioPorNoche = 75.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            CapacidadPersonas = 4,
                            Descripcion = "Suite de lujo con jacuzzi",
                            Estado = 0,
                            Numero = "201",
                            PrecioPorNoche = 150.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 4,
                            CapacidadPersonas = 6,
                            Descripcion = "Habitación familiar amplia",
                            Estado = 0,
                            Numero = "202",
                            PrecioPorNoche = 120.00m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 5,
                            CapacidadPersonas = 2,
                            Descripcion = "Habitación doble estándar",
                            Estado = 0,
                            Numero = "301",
                            PrecioPorNoche = 80.00m,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Huesped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Huespedes");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CuartoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CuartoId");

                    b.HasIndex("HuespedId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$ZqBBKLPRkKWPKKb9VIjwuuQXw4QmuWEezea2ii17Dgd5xcum.YjGG",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "usuario",
                            PasswordHash = "$2a$11$UDvpK6D8kalEmHUVI1kxduAC9pXBvwk.J7g5k01MdIQEYh2z6/93G",
                            Rol = "Usuario"
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Reserva", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Cuarto", "Cuarto")
                        .WithMany("Reservas")
                        .HasForeignKey("CuartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.Huesped", "Huesped")
                        .WithMany("Reservas")
                        .HasForeignKey("HuespedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuarto");

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Cuarto", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Huesped", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
