// <auto-generated />
using System;
using HotelManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.Server.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251208174138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelManagement.API.Models.Cuarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Cuartos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadPersonas = 1,
                            Descripcion = "Habitación individual con vista a la ciudad",
                            Estado = 1,
                            Numero = "101",
                            PrecioPorNoche = 50.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            CapacidadPersonas = 2,
                            Descripcion = "Habitación doble con cama queen size",
                            Estado = 1,
                            Numero = "102",
                            PrecioPorNoche = 80.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            CapacidadPersonas = 3,
                            Descripcion = "Suite con sala de estar y jacuzzi",
                            Estado = 1,
                            Numero = "201",
                            PrecioPorNoche = 150.00m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 4,
                            CapacidadPersonas = 4,
                            Descripcion = "Habitación familiar con dos camas dobles",
                            Estado = 1,
                            Numero = "202",
                            PrecioPorNoche = 120.00m,
                            Tipo = 4
                        },
                        new
                        {
                            Id = 5,
                            CapacidadPersonas = 4,
                            Descripcion = "Suite presidencial con todas las comodidades",
                            Estado = 1,
                            Numero = "301",
                            PrecioPorNoche = 300.00m,
                            Tipo = 5
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Huesped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Huespedes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direccion = "Calle Mayor 1, Madrid",
                            DocumentoIdentidad = "12345678A",
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2025, 9, 8, 18, 41, 37, 543, DateTimeKind.Local).AddTicks(1118),
                            Nombre = "Juan",
                            Telefono = "+34-600-123-456"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "García",
                            Direccion = "Avenida Principal 45, Barcelona",
                            DocumentoIdentidad = "87654321B",
                            Email = "maria.garcia@email.com",
                            FechaRegistro = new DateTime(2025, 10, 8, 18, 41, 37, 543, DateTimeKind.Local).AddTicks(1131),
                            Nombre = "María",
                            Telefono = "+34-600-789-012"
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CuartoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HuespedId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CuartoId");

                    b.HasIndex("HuespedId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Reserva", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Cuarto", "Cuarto")
                        .WithMany("Reservas")
                        .HasForeignKey("CuartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.Huesped", "Huesped")
                        .WithMany("Reservas")
                        .HasForeignKey("HuespedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuarto");

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Cuarto", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Huesped", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
